@eccormerce_HostAddress = http://localhost:5099

Post {{eccormerce_HostAddress}}/api/account/register
Accept: application/json

###
Post {{eccormerce_HostAddress}}/api/account/login
Accept: application/json

###
POST  {{eccormerce_HostAddress}}/api/account/logout
Accept: application/json

###
POST  {{eccormerce_HostAddress}}/api/account/refresh
Accept: application/json
